/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.List;
import java.util.Map;
import model.ModelAccount;
import model.ModelReceiveMessage;
import model.ModelSendMessage;
import net.miginfocom.swing.MigLayout;
import service.Service;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JLayeredPane {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        init();
    }
    private Chat chat;


    public void setListSendMessage(List<ModelSendMessage> listSendMessage) {
        chat.setListSendMessage(listSendMessage); 
    }


    public void setListReceiveMessage(List<ModelReceiveMessage> listReceiveMessage) {
        chat.setListReceiveMessage(listReceiveMessage);
    }
    private void init() {
        setLayout(new MigLayout("fillx, filly", "0[200!]5[fill, 100%]0","0[fill]0"));
        this.add(new MenuLeft());
        chat = new Chat();
        this.add(chat);
//        this.add(new MenuRight()); 
        chat.setVisible(false);
    }
    public void setUser(ModelAccount user){
        chat.setUser(user);
        chat.setVisible(true);
    }
    
    public void updateUser(ModelAccount user){
        chat.updateUser(user);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
