/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author Admin
 */
public class ChatLeftWithProfile extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatLeft
     */
    public ChatLeftWithProfile() {
        initComponents();
        txt.setBackground(new Color(225,225,225));
    }
    
    public void setUserProfile(String user) {
        txt.setUserProfile(user);
    }
    
    public void setImage(Icon image) {
        img.setImage(image);
    }
    
    public void setText(String text){
        if(text.equals("")){
            txt.hintText();
        }else{
            txt.setText(text);
        }
        
    }
    
    public void setImage(Icon... images) {
//        txt.setImage(false, images);
    }
    
    public void setImage(String... images) {
//        txt.setImage(false, images);
    }
    
//    public void setFile(String fileName, String size){
//        txt.setFile(false,fileName, size);
//    }
    
    public void setTime(String time) {
        txt.setTime(time);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        img = new swing.ImageAvatar();
        txt = new component.ChatItem();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        img.setBorderSize(0);
        img.setImage(new javax.swing.ImageIcon(getClass().getResource("/assets/testing/dog.jpg"))); // NOI18N
        img.setMaximumSize(new java.awt.Dimension(31, 31));
        img.setMinimumSize(new java.awt.Dimension(31, 31));
        img.setPreferredSize(new java.awt.Dimension(31, 31));

        jLayeredPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jLayeredPane1);
        add(txt);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ImageAvatar img;
    private javax.swing.JLayeredPane jLayeredPane1;
    private component.ChatItem txt;
    // End of variables declaration//GEN-END:variables
}
