/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import event.PublicEvent;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import model.ModelFileSender;
import model.ModelReceiveImage;
import model.ModelReceiveMessage;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Admin
 */
public class ChatImage extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatImage
     */
    public ChatImage(boolean right) {
        initComponents();
        setLayout(new MigLayout("", "0[" + (right ? "right" : "left") + "]0", "3[]3"));
    }
    
    public void addImage(ModelFileSender fileSender) {
        Icon image = new ImageIcon(fileSender.getFile().getAbsolutePath());
        ImageItem pic = new ImageItem();
        pic.setPreferredSize(getAutoSize(image, 200, 200));
        pic.setImage(image,fileSender);
        addEvent(pic, image,fileSender.getFile().getAbsolutePath());
        add(pic,"wrap");
        
    }
    
    public void addImage(ModelReceiveMessage message,ModelReceiveImage dataImage) {
        ImageItem pic = new ImageItem();
        pic.setPreferredSize(new Dimension(dataImage.getWidth(),dataImage.getHeight()));
        pic.setImage(message,dataImage);
        add(pic,"wrap");   
    }
    
    public void addImage(String pathImage) {
        ImageItem pic = new ImageItem();
        pic.setPreferredSize(new Dimension(200,200));
        pic.setImage(pathImage);
        add(pic,"wrap");   
    }
    
    private void addEvent(Component com, Icon image,String filePath){
        com.setCursor(new Cursor(Cursor.HAND_CURSOR));
        com.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                if(SwingUtilities.isLeftMouseButton(e)){
                    PublicEvent.getInstance().getEventImageView().viewImage(image,filePath);
                }
            }
            
        });
    }
    
    private Dimension getAutoSize(Icon image, int w, int h) {
        if( w> image.getIconWidth()){
            w = image.getIconWidth();
        }
        if(h > image.getIconHeight()) {
            h = image.getIconHeight();
        }
        int iw = image.getIconWidth();
        int ih = image.getIconHeight();
        double xScale = (double) w / iw;
        double yScale = (double) h / ih;
        double scale = Math.min(xScale, yScale);
        int width = (int) (scale * iw);
        int height = (int) (scale * ih);
        return  new Dimension(width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
