/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import model.ModelAccount;
import service.Service;
import view.CallVideo;

/**
 *
 * @author Admin
 */
public class ChatTitle extends javax.swing.JPanel {

    /**
     * Creates new form ChatTitle
     */
    public ChatTitle() {
        initComponents();
    }
    private ModelAccount user;

    public ModelAccount getUser() {
        return user;
    }
    
    

    public void setUser(ModelAccount user) {
        this.user = user;
        lbName.setText(user.getUserName());
        if(user.isStatus()){
            setStatus();
        }else{
            setStatusText("Không hoạt động");
        }
    }
    
    public void updateUser(ModelAccount user) {
        if(this.user==null) {
            setUser(user);return;
        }
        if(this.user.getUserID()==user.getUserID()){
            lbName.setText(user.getUserName());
            if(user.isStatus()){
                setStatus();
            }else{
                setStatusText("Không hoạt động");
            }
        }
        
    }
        
    public void setStatus(){
        lbStatus.setText("Đang hoạt động");
        lbStatus.setForeground(new Color(54,186,44));
        repaint();
        revalidate();
    }
    
    public void setStatusText(String text) {
        lbStatus.setText(text);
        lbStatus.setForeground(new Color(160,160,160));
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new javax.swing.JLayeredPane();
        lbName = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(225, 225, 225));

        layer.setLayout(new java.awt.GridLayout(0, 1));

        lbName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbName.setText("Tên:");
        layer.add(lbName);

        lbStatus.setForeground(new java.awt.Color(54, 186, 44));
        lbStatus.setText("Đang hoạt động");
        layer.add(lbStatus);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emojiicon/icon/call.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layer, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layer)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Service.getInstance().callToUser(user);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane layer;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbStatus;
    // End of variables declaration//GEN-END:variables
}
