/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import javax.swing.Icon;
import model.ModelFileSender;

/**
 *
 * @author Admin
 */
public class ChatRight extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatLeft
     */
    public ChatRight() {
        initComponents();
        txt.setBackground(new Color(179, 233, 255));
    }
    
    public void setText(String text){
        if(text.equals("")){
            txt.hintText();
        }else{
            txt.setText(text);
        }
        txt.seen();
    }
    
    public void setImage(ModelFileSender fileSender) {
        txt.setImage(true, fileSender);
    }
    
    public void setImage(String imagePath) {
        txt.setImage(true, imagePath);
    }
    
    public void setImage(String... images) {
//        txt.setImage(false, images);
    }
    
//    public void setFile(String fileName, String size){
//        txt.setFile(true,fileName, size);
//    }
    
    public void setFile(ModelFileSender fileSender){
        txt.setFile(true,fileSender);
    }
    
    public void setFile(String filePath){
        txt.setFile(true,filePath);
    }
    
    public void setEmoji(Icon icon){
        txt.hintText();
        txt.setEmoji(true, icon);
    }
    
    public void setTime(String time) {
        txt.setTime(time);
    }
    
    public void sendSuccess(){
        txt.sendSuccess();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new component.ChatItem();

        setLayer(txt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.ChatItem txt;
    // End of variables declaration//GEN-END:variables
}
